name: cauldron_quest
description: Looking at board-game winrates.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  stats: ^2.0.0
  a_star:
    git: git@github.com:sethladd/dart-a-star.git

dev_dependencies:
  test: ^1.16.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true